
FROM nginx
MAINTAINER gh gh@sywh.com
 # 更新 163 源
 RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
     echo "deb http://mirrors.163.com/debian/ jessie main non-free contrib" >/etc/apt/sources.list && \
     echo "deb http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list && \
     echo "deb-src http://mirrors.163.com/debian/ jessie main non-free contrib" >>/etc/apt/sources.list && \
     echo "deb-src http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list


 # install essential Linux packages
 RUN apt-get update -qq && apt-get -y install apache2-utils vim

 # establish where Nginx should look for files
 ENV RAILS_ROOT /app

 # Set our working directory inside the image
 WORKDIR $RAILS_ROOT

 # create log directory
 RUN mkdir log

 # copy over static assets
 # 这一步实做时，复制是复制到 nginx 容器中的 public 文件夹下
 # 但静态资料却显示不了,最后在 docker-compose 文件中设置了 volumes 才可以
 # 可能是哪个地方我没有设置正确。
 COPY public public/

 # copy our Nginx config template
 COPY dockerfiles/nginx/nginx.conf /tmp/eshop.nginx

 # substitute variable references in the Nginx config template for real values from the environment
 # put the final config in its place
 RUN envsubst '$RAILS_ROOT' < /tmp/eshop.nginx > /etc/nginx/conf.d/default.conf

 # Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
 CMD [ "nginx", "-g", "daemon off;" ]
