#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          sywh_back
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the sywh_back server
# Description:       Start and stop the sywh_back server
### END INIT INFO
#

#set -e
#chkconfig: 345 99 76

USAGE="Usage: $0 <start|stop|restart>"

# app settings
USER="sywh"
APP_NAME="sywh_back"
APP_ROOT="/home/$USER/$APP_NAME"
ENV="production"

# environment settings
PATH="/home/$USER/.rbenv/shims:/home/$USER/.rbenv/bin:$PATH"
START="cd $APP_ROOT && bundle exec puma -C config/puma.rb -e $ENV -d"
STOP="cd $APP_ROOT && bundle exec pumactl -P tmp/pids/puma.pid stop"
RESTART="cd $APP_ROOT && bundle exec pumactl -P tmp/pids/puma.pid restart"

# make sure the app exists
cd $APP_ROOT || exit 1

case $1 in
  start)
    echo "Starting $APP_NAME"
    su - $USER -c "$START"
    ;;
  stop)
    echo "Stopping $APP_NAME"
    su - $USER -c "$STOP"
    ;;
  restart)
    echo "Restarting $APP_NAME"
    su - $USER -c "$RESTART"
    ;;
  *)
    echo >&2 $USAGE
    exit 1
    ;;
esac
